# Generated by Django 4.1.7 on 2023-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('emp_code', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('postion', models.CharField(max_length=100)),
            ],
        ),
    ]
